### ISSUE TITLE
Clarify requested timezone

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/dockless-bikeshare-reporting-manual#22]
The requirement for dates is still ambiguous. We are requiring ISO 8601, but do not state the format or timezone. I'd recommend that we require the timezone with offset, e.g., `YYYY-MM-DDTHH:MM:SS+00:00`.

**Comment by nicklucius** [comment]
Closed with https://github.com/Chicago/dockless-bikeshare-reporting-manual/pull/27
