### ISSUE TITLE
Determine due dates

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/dockless-bikeshare-reporting-manual#3]
One of the remaining items is to determine the due dates for the files to be submitted and verified. I'd like to propose 10 days after the beginning of the month. I hope to avoid the sometimes overlap with the TNP reporting due dates and the earlier dates can be justified by the relatively simpler reporting requirements.

If that was the case, this would be the due dates:

  * June 11th
  * July 10th
  * August 10th
  * September 10th
  * October 10th
 
For October/November, since the reporting period is inclusive of November 1st, we can push one more day so that reporting deadline is November 12th (due to the weekend).

Thoughts, @nicklucius @levyj?

**Comment by levyj** [comment]
Works for me. I think the key is what the companies can do without excessive burden. Obviously, we cannot be completely flexible but if a small amount of extra time makes a big difference to them, I don't object. That said, someone else within the overall City of Chicago team may be more sensitive to a delay for some reason.

Have we worked out *how* the files are to be delivered? If not, that may merit a separate issue in this repo.

**Comment by tomschenkjr** [comment]
Ah! Thanks for bringing up how to transfer, everyone agreed on S3 (no firewall rules!)

In the TNP, we didn't specify the upload method, so I didn't here. I figure we can do that offline with them ("here are the keys, go upload").

_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
(312) 744-2770
tom.schenk@cityofchicago.org | @ChicagoCDO
data.cityofchicago.org | opengrid.io | digital.cityofchicago.org | chicago.github.io | dev.cityofchicago.org


________________________________

**Comment by nicklucius** [comment]
To me it's a reasonable timeline. I would imagine that at first it could take longer to set up, as there will need to be some data manipulation by the companies to transform their data to the specs. But that should be a one-time problem. Meeting the reporting requirements should ideally be something that can be performed in just a few minutes with simple commands. 10 calendar days guarantees there will always be a full week to work it out.

It would probably be a good idea to draw the companies' attention to the first deadline of **June 11** right now to make sure they are ready.
