### ISSUE TITLE
Trips file has a sentence fragment

### ISSUE THREAD

**Issue by levyj** [Chicago/dockless-bikeshare-reporting-manual#4]
Just so it does not get missed.

https://github.com/Chicago/dockless-bikeshare-reporting-manual/commit/b21280396dd9abd3f7691e2fa406b95e369dd733#L9

(That is supposed to link to the relevant line, although it is not clear to me that it is working.)

@tomschenkjr

**Comment by tomschenkjr** [comment]
@levyj - it's very clear that "Trips that end" was used in a metaphysical sense, _a la_ Jacques Derrida.
